# Generated by Django 5.1.5 on 2025-08-30 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name_1', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('last_name_2', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('RUN', models.CharField(help_text='Ejemplo: 12345678-9', max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUN')),
                ('email', models.EmailField(help_text=' Ejemplo: correo@ejemplo.com', max_length=100, verbose_name='Correo electrónico')),
                ('phone', models.CharField(help_text='Ejemplo: +56912345678', max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\+1?\\d{9,15}$')], verbose_name='Teléfono/Celular')),
                ('address', models.CharField(help_text='Ingrese una dirección, máximo de 200 caracteres', max_length=200, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'permissions': [('create_client', 'Puede agregar clientes'), ('read_client', 'Puede ver clientes'), ('update_client', 'Puede modificar clientes'), ('export_client', 'Puede exportar clientes')],
            },
        ),
    ]
