# Generated by Django 5.1.5 on 2025-08-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('export_client', 'Puede exportar clientes')]},
        ),
    ]
