# Generated by Django 5.1.5 on 2025-08-31 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_client_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='RUN',
            new_name='run',
        ),
    ]
