# Generated by Django 5.1.5 on 2025-09-17 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_phone_client_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoSII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=6, verbose_name='Código Actividad S.I.I.')),
                ('activity', models.CharField(max_length=100, verbose_name='Actividad Económica')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Región')),
            ],
        ),
        migrations.CreateModel(
            name='RegTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Régimen Tributario')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de Contabilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Claves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sii', models.CharField(max_length=70, verbose_name='Clave S.I.I.')),
                ('factura_electronica', models.CharField(max_length=70, verbose_name='Clave Factura Electrónica')),
                ('dir_trabajo', models.CharField(max_length=70, verbose_name='Clave Dirección de Trabajo')),
                ('unica', models.CharField(max_length=70, verbose_name='Clave Única')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestion.region', verbose_name='Región')),
            ],
        ),
    ]
