# Generated by Django 5.1.5 on 2025-09-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_codigosii_region_regtributario_tipocontabilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigosii',
            name='code',
            field=models.IntegerField(verbose_name='Código Actividad S.I.I.'),
        ),
    ]
