# Generated by Django 5.1.5 on 2025-09-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_codigosii_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regtributario',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Régimen Tributario'),
        ),
    ]
