# Generated by Django 5.1.5 on 2025-09-18 17:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_regtributario_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='last_name_1',
            new_name='last_name_1_rep_legal',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='last_name_2',
            new_name='last_name_2_rep_legal',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='nombre_rep_legal',
        ),
        migrations.RemoveField(
            model_name='client',
            name='run',
        ),
        migrations.AddField(
            model_name='client',
            name='codigo_sii',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='gestion.codigosii', verbose_name='Código Actividad S.I.I.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='gestion.comuna', verbose_name='Comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='cuenta_corriente',
            field=models.CharField(choices=[('bice', 'Banco Bice'), ('consorcio', 'Banco Consorcio'), ('chile', 'Banco De Chile'), ('estado', 'Banco Del Estado De Chile'), ('falabella', 'Banco Falabella'), ('internacional', 'Banco Internacional'), ('itau', 'Banco Itaú Chile'), ('ripley', 'Banco Ripley'), ('santander Chile', 'Banco Santander Chile'), ('security', 'Banco Security'), ('bci', 'Banco Bci'), ('scotiabank', 'Scotiabank Chile'), ('btg_pactual', 'Btg Pactual Chile')], default=1, max_length=30, verbose_name='Cuenta Corriente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='giro_rubro',
            field=models.CharField(choices=[('agricultura', 'Agricultura, Ganadería, Silvicultura Y Pesca'), ('explotacion_minas', 'Explotación De Minas Y Canteras'), ('i_manufacturera', 'Industria Manufacturera'), ('sum_electricidad', 'Suministro De Electricidad, Gas, Vapor Y Aire Acondicionado'), ('sum_agua', 'Suministro De Agua; Evacuación De Aguas Residuales, Gestión De Desechos Y Descontaminación'), ('construccion', 'Construcción'), ('comercio_reparacion', 'Comercio Al Por Mayor Y Al Por Menor; Reparación De Vehiculos Automotores Y Motocicletas'), ('transporte_almacenamiento', 'Transporte Y Almacenamiento'), ('act_alojamiento', 'Actividades De Alojamiento Y De Servicio De Comidas'), ('info_com', 'Información Y Comunicaciones'), ('act_financieras', 'Actividades Financieras Y De Seguros'), ('act_inmobiliarias', 'Actividades Inmobiliarias'), ('act_profesionales', 'Actividades Profesionales, Cientificas Y Técnicas'), ('act_administrativos', 'Actividades De Servicios Administrativos Y De Apoyo'), ('admin_publica', 'Administración Pública Y Defensa; Planes De Seguridad Social De Afiliación Obligatoria'), ('ensenianza', 'Enseñanza'), ('act_atención_salud', 'Actividades De Atención De La Salud Humana Y De Asistencia Social'), ('act_artisticas', 'Actividades Artísticas, De Entretenimiento Y Recreativas'), ('otras_act_servicios', 'Otras Actividades De Servicios'), ('act_hogares', 'Actividades De Los Hogares Como Empleadores; Actividades No Diferenciadas De Los Hogares'), ('act_organizaciones', 'Actividades De Organizaciones Y Órganos Extraterritoriales')], default=1, max_length=100, verbose_name='Giro / Rubro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='n_cuenta_corriente',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.RegexValidator(regex='^(\\d+|\\d{1,3}(?:-\\d{1,3})+|\\d{1,3}(?: \\d{1,3})+)$')], verbose_name='N° Cuenta Corriente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre de Fantasía'),
        ),
        migrations.AddField(
            model_name='client',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='gestion.region', verbose_name='Región'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='run_empresa',
            field=models.CharField(default=1, help_text='Ejemplo: 12345678-9', max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUN (Empresa)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='run_rep_legal',
            field=models.CharField(default=1, help_text='Ejemplo: 12345678-9', max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUN (Representante legal)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='tipo_contabilidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='gestion.tipocontabilidad', verbose_name='Tipo de Contabilidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='tipo_empresa',
            field=models.CharField(choices=[('p_natural', 'Persona Natural'), ('p_juridica', 'Persona Jurídica')], default=1, max_length=20, verbose_name='Tipo de empresa'),
            preserve_default=False,
        ),
    ]
