# Generated by Django 5.1.5 on 2025-09-18 18:08

import django.core.validators
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_rename_last_name_1_client_last_name_1_rep_legal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='n_cuenta_corriente',
            field=models.CharField(error_messages={'invalid': 'Solo se permiten dígitos y espacios o guiones (-)'}, max_length=20, validators=[django.core.validators.RegexValidator(regex=[gestion.models.cuenta_corriente_validator])], verbose_name='N° Cuenta Corriente'),
        ),
    ]
