# Generated by Django 5.1.5 on 2025-09-18 18:22

import django.core.validators
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_client_n_cuenta_corriente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='n_cuenta_corriente',
            field=models.CharField(error_messages={'invalid': 'Solo se permiten dígitos y espacios o guiones (-)'}, max_length=20, validators=[gestion.models.cuenta_corriente_validator], verbose_name='N° Cuenta Corriente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre_rep_legal',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='\\D[a-zA-Z]{3,}+')], verbose_name='Nombre'),
        ),
    ]
