# Generated by Django 5.1.5 on 2025-09-18 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_client_n_cuenta_corriente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nombre_rep_legal',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='\\D[a-zA-Z]{2,}+')], verbose_name='Nombre'),
        ),
    ]
