# Generated by Django 5.1.5 on 2025-09-18 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_client_nombre_rep_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(help_text='Ingrese una dirección, máximo de 200 caracteres', max_length=200, validators=[django.core.validators.RegexValidator(regex='\\D[a-zA-Z]{2,}+')], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name_1_rep_legal',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='\\D[a-zA-Z]{2,}+')], verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name_2_rep_legal',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='\\D[a-zA-Z]{2,}+')], verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(regex='\\D[a-zA-Z]{2,}+')], verbose_name='Nombre de Fantasía'),
        ),
        migrations.AlterField(
            model_name='client',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(regex='\\D[a-zA-Z]{2,}+')], verbose_name='Razón Social'),
        ),
    ]
