# Generated by Django 5.1.5 on 2025-09-19 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reg_tributario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='gestion.regtributario', verbose_name='Régimen Tributario'),
            preserve_default=False,
        ),
    ]
