# Generated by Django 5.1.5 on 2025-09-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_client_reg_tributario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claves',
            name='dir_trabajo',
            field=models.CharField(max_length=130, verbose_name='Clave Dirección de Trabajo'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='factura_electronica',
            field=models.CharField(max_length=130, verbose_name='Clave Factura Electrónica'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='sii',
            field=models.CharField(max_length=130, verbose_name='Clave S.I.I.'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='unica',
            field=models.CharField(max_length=130, verbose_name='Clave Única'),
        ),
    ]
