# Generated by Django 5.1.5 on 2025-09-20 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_claves_dir_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(help_text='Ejemplo: +56912345678', max_length=18, validators=[django.core.validators.RegexValidator(regex='^\\+1?\\d{9,15}$')], verbose_name='Teléfono/Celular'),
        ),
    ]
