# Generated by Django 5.1.5 on 2025-09-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cuenta_corriente',
            field=models.CharField(choices=[('Banco Bice', 'Banco Bice'), ('Banco Consorcio', 'Banco Consorcio'), ('Banco De Chile', 'Banco De Chile'), ('Banco Del Estado De Chile', 'Banco Del Estado De Chile'), ('Banco Falabella', 'Banco Falabella'), ('Banco Internacional', 'Banco Internacional'), ('Banco Itaú Chile', 'Banco Itaú Chile'), ('Banco Ripley', 'Banco Ripley'), ('Banco Santander Chile', 'Banco Santander Chile'), ('Banco Security', 'Banco Security'), ('Banco Bci', 'Banco Bci'), ('Scotiabank Chile', 'Scotiabank Chile'), ('Btg Pactual Chile', 'Btg Pactual Chile')], max_length=30, verbose_name='Cuenta Corriente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='giro_rubro',
            field=models.CharField(choices=[('Agricultura, Ganadería, Silvicultura Y Pesca', 'Agricultura, Ganadería, Silvicultura Y Pesca'), ('Explotación De Minas Y Canteras', 'Explotación De Minas Y Canteras'), ('Industria Manufacturera', 'Industria Manufacturera'), ('Suministro De Electricidad, Gas, Vapor Y Aire Acondicionado', 'Suministro De Electricidad, Gas, Vapor Y Aire Acondicionado'), ('Suministro De Agua; Evacuación De Aguas Residuales, Gestión De Desechos Y Descontaminación', 'Suministro De Agua; Evacuación De Aguas Residuales, Gestión De Desechos Y Descontaminación'), ('Construcción', 'Construcción'), ('Comercio Al Por Mayor Y Al Por Menor; Reparación De Vehiculos Automotores Y Motocicletas', 'Comercio Al Por Mayor Y Al Por Menor; Reparación De Vehiculos Automotores Y Motocicletas'), ('Transporte Y Almacenamiento', 'Transporte Y Almacenamiento'), ('Actividades De Alojamiento Y De Servicio De Comidas', 'Actividades De Alojamiento Y De Servicio De Comidas'), ('Información Y Comunicaciones', 'Información Y Comunicaciones'), ('Actividades Financieras Y De Seguros', 'Actividades Financieras Y De Seguros'), ('Actividades Inmobiliarias', 'Actividades Inmobiliarias'), ('Actividades Profesionales, Cientificas Y Técnicas', 'Actividades Profesionales, Cientificas Y Técnicas'), ('Actividades De Servicios Administrativos Y De Apoyo', 'Actividades De Servicios Administrativos Y De Apoyo'), ('Administración Pública Y Defensa; Planes De Seguridad Social De Afiliación Obligatoria', 'Administración Pública Y Defensa; Planes De Seguridad Social De Afiliación Obligatoria'), ('Enseñanza', 'Enseñanza'), ('Actividades De Atención De La Salud Humana Y De Asistencia Social', 'Actividades De Atención De La Salud Humana Y De Asistencia Social'), ('Actividades Artísticas, De Entretenimiento Y Recreativas', 'Actividades Artísticas, De Entretenimiento Y Recreativas'), ('Otras Actividades De Servicios', 'Otras Actividades De Servicios'), ('Actividades De Los Hogares Como Empleadores; Actividades No Diferenciadas De Los Hogares', 'Actividades De Los Hogares Como Empleadores; Actividades No Diferenciadas De Los Hogares'), ('Actividades De Organizaciones Y Órganos Extraterritoriales', 'Actividades De Organizaciones Y Órganos Extraterritoriales')], max_length=100, verbose_name='Giro / Rubro'),
        ),
    ]
