# Generated by Django 5.1.5 on 2025-09-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_client_cuenta_corriente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claves',
            name='iv',
            field=models.BinaryField(auto_created=True, default=b'\xb7X\x9b\xc2\xf7\xab_\xf1H\x99\xd5o0\x8c\xc4\x89'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tipo_empresa',
            field=models.CharField(choices=[('Persona Natural', 'Persona Natural'), ('Persona Jurídica', 'Persona Jurídica')], max_length=20, verbose_name='Tipo de empresa'),
        ),
    ]
