# Generated by Django 5.1.5 on 2025-09-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_claves_iv_alter_client_tipo_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claves',
            name='iv',
            field=models.BinaryField(auto_created=True),
        ),
    ]
