# Generated by Django 5.1.5 on 2025-09-21 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_alter_claves_iv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claves',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.client', verbose_name='Cliente'),
        ),
    ]
