# Generated by Django 5.1.5 on 2025-09-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alter_claves_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claves',
            name='dir_trabajo',
            field=models.BinaryField(editable=True, verbose_name='Clave Dirección de Trabajo'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='factura_electronica',
            field=models.BinaryField(editable=True, verbose_name='Clave Factura Electrónica'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='sii',
            field=models.BinaryField(editable=True, verbose_name='Clave S.I.I.'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='unica',
            field=models.BinaryField(editable=True, verbose_name='Clave Única'),
        ),
    ]
