# Generated by Django 5.1.5 on 2025-09-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_alter_claves_dir_trabajo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiroRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Giro / Rubro')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='n_trabajadores',
            field=models.IntegerField(default=5, verbose_name='Trabajadores'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='client',
            name='giro_rubro',
        ),
        migrations.RemoveField(
            model_name='client',
            name='reg_tributario',
        ),
        migrations.AddField(
            model_name='client',
            name='giro_rubro',
            field=models.ManyToManyField(to='gestion.girorubro', verbose_name='Giro / Rubro'),
        ),
        migrations.AddField(
            model_name='client',
            name='reg_tributario',
            field=models.ManyToManyField(to='gestion.regtributario', verbose_name='Régimen Tributario'),
        ),
    ]
