# Generated by Django 5.1.5 on 2025-09-28 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_girorubro_client_n_trabajadores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compras', models.IntegerField()),
                ('ventas', models.IntegerField()),
                ('retenciones', models.IntegerField()),
                ('a_pagar', models.IntegerField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.client', verbose_name='Cliente')),
            ],
        ),
    ]
