# Generated by Django 5.1.5 on 2025-09-28 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_pagoscliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pagoscliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagoscliente',
            name='honorarios',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagoscliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='dir_trabajo',
            field=models.CharField(max_length=150, verbose_name='Dirección de Trabajo'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='factura_electronica',
            field=models.CharField(max_length=150, verbose_name='Factura Electrónica'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='sii',
            field=models.CharField(max_length=150, verbose_name='S.I.I.'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='codigo_sii',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tipo_contabilidad',
        ),
        migrations.AddField(
            model_name='client',
            name='codigo_sii',
            field=models.ManyToManyField(to='gestion.codigosii', verbose_name='Código Actividad S.I.I.'),
        ),
        migrations.AddField(
            model_name='client',
            name='tipo_contabilidad',
            field=models.ManyToManyField(to='gestion.tipocontabilidad', verbose_name='Tipo de Contabilidad'),
        ),
    ]
