# Generated by Django 5.1.5 on 2025-10-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_remove_client_created_at_remove_client_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagoscliente',
            old_name='compras',
            new_name='f301',
        ),
        migrations.RenameField(
            model_name='pagoscliente',
            old_name='retenciones',
            new_name='imposiciones',
        ),
        migrations.RenameField(
            model_name='pagoscliente',
            old_name='ventas',
            new_name='iva_a_pagar',
        ),
        migrations.RemoveField(
            model_name='pagoscliente',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pagoscliente',
            name='iva_anticipado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagoscliente',
            name='otros',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagoscliente',
            name='ppm_vehiculo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagoscliente',
            name='ppm_ventas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pagoscliente',
            name='client',
        ),
        migrations.AddField(
            model_name='pagoscliente',
            name='client',
            field=models.ManyToManyField(to='gestion.client', verbose_name='Cliente'),
        ),
    ]
