# Generated by Django 5.1.5 on 2025-10-10 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_rename_compras_pagoscliente_f301_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='run_empresa',
            field=models.CharField(help_text='Ejemplo: 12345678-9', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUN (Empresa)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='run_rep_legal',
            field=models.CharField(help_text='Ejemplo: 12345678-9', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUN (Representante legal)'),
        ),
    ]
