# Generated by Django 5.1.5 on 2025-10-19 22:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_alter_client_run_empresa_alter_client_run_rep_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='run_empresa',
            field=models.CharField(help_text='Ejemplo: 12345678-9', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUT (Empresa)'),
        ),
        migrations.AlterField(
            model_name='pagoscliente',
            name='a_pagar',
            field=models.IntegerField(verbose_name='A Pagar'),
        ),
        migrations.RemoveField(
            model_name='pagoscliente',
            name='client',
        ),
        migrations.AlterField(
            model_name='pagoscliente',
            name='f301',
            field=models.IntegerField(verbose_name='F30-1'),
        ),
        migrations.AlterField(
            model_name='pagoscliente',
            name='honorarios',
            field=models.IntegerField(verbose_name='Honorarios'),
        ),
        migrations.AlterField(
            model_name='pagoscliente',
            name='imposiciones',
            field=models.IntegerField(verbose_name='Imposiciones'),
        ),
        migrations.AlterField(
            model_name='pagoscliente',
            name='iva_a_pagar',
            field=models.IntegerField(verbose_name='IVA a Pagar'),
        ),
        migrations.AlterField(
            model_name='pagoscliente',
            name='iva_anticipado',
            field=models.IntegerField(verbose_name='IVA Anticipado'),
        ),
        migrations.AlterField(
            model_name='pagoscliente',
            name='otros',
            field=models.IntegerField(verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='pagoscliente',
            name='ppm_vehiculo',
            field=models.IntegerField(verbose_name='PPM de Vehículo'),
        ),
        migrations.AlterField(
            model_name='pagoscliente',
            name='ppm_ventas',
            field=models.IntegerField(verbose_name='PPM de Ventas'),
        ),
        migrations.AddField(
            model_name='pagoscliente',
            name='client',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='gestion.client', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
