# Generated by Django 5.1.5 on 2025-10-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_alter_client_run_empresa_alter_pagoscliente_a_pagar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoscliente',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagoscliente',
            name='f301',
            field=models.IntegerField(verbose_name='Certificado F30-1'),
        ),
        migrations.AlterField(
            model_name='pagoscliente',
            name='ppm_vehiculo',
            field=models.IntegerField(verbose_name='PPM Sobre Vehículo'),
        ),
        migrations.AlterField(
            model_name='pagoscliente',
            name='ppm_ventas',
            field=models.IntegerField(verbose_name='PPM Sobre las Ventas'),
        ),
    ]
