# Generated by Django 5.1.5 on 2025-10-25 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_pagoscliente_total_alter_pagoscliente_f301_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claves',
            name='client',
            field=models.OneToOneField(help_text='Asegúrese de que el cliente seleccionado sea correcto', on_delete=django.db.models.deletion.CASCADE, to='gestion.client', verbose_name='Cliente'),
        ),
    ]
