# Generated by Django 5.1.5 on 2025-10-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_alter_claves_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claves',
            name='iv',
            field=models.BinaryField(),
        ),
    ]
