# Generated by Django 5.1.5 on 2025-10-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_alter_claves_iv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claves',
            name='dir_trabajo',
            field=models.BinaryField(editable=True, max_length=150, verbose_name='Dirección de Trabajo'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='factura_electronica',
            field=models.BinaryField(editable=True, max_length=150, verbose_name='Factura Electrónica'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='sii',
            field=models.BinaryField(editable=True, max_length=150, verbose_name='S.I.I.'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='unica',
            field=models.BinaryField(editable=True, max_length=150, verbose_name='Clave Única'),
        ),
    ]
