# Generated by Django 5.1.5 on 2025-10-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_alter_claves_dir_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claves',
            name='dir_trabajo',
            field=models.TextField(verbose_name='Dirección de Trabajo'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='factura_electronica',
            field=models.TextField(verbose_name='Factura Electrónica'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='sii',
            field=models.TextField(verbose_name='S.I.I.'),
        ),
        migrations.AlterField(
            model_name='claves',
            name='unica',
            field=models.TextField(verbose_name='Clave Única'),
        ),
    ]
