# Generated by Django 5.2.7 on 2025-10-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0032_alter_claves_dir_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claves',
            options={'permissions': [('export_claves', 'Puede exportar claves')]},
        ),
        migrations.AlterModelOptions(
            name='pagoscliente',
            options={'permissions': [('export_pagos', 'Puede exportar pagos')]},
        ),
    ]
