# Generated by Django 5.2.7 on 2025-10-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0033_alter_claves_options_alter_pagoscliente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoscliente',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
