# Generated by Django 5.2.7 on 2025-10-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0034_alter_pagoscliente_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoscliente',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
