# Generated by Django 5.2.7 on 2025-10-31 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0035_alter_pagoscliente_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='run_empresa',
            field=models.CharField(help_text='Ejemplo: 12345678-9', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUT/RUN (Empresa)'),
        ),
    ]
