# Generated by Django 5.2.7 on 2025-11-09 19:53

import django.core.validators
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0037_alter_pagoscliente_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(help_text='Ingrese una dirección, máximo de 200 caracteres', max_length=200, validators=[django.core.validators.RegexValidator(code='invalid', message='Solo se aceptan caracteres, y un mínimo de 2', regex='\\D[a-zA-Z]{2,}+')], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name_1_rep_legal',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid', message='Solo se aceptan caracteres, y un mínimo de 2', regex='\\D[a-zA-Z]{2,}+')], verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name_2_rep_legal',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid', message='Solo se aceptan caracteres, y un mínimo de 2', regex='\\D[a-zA-Z]{2,}+')], verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='client',
            name='n_cuenta_corriente',
            field=models.CharField(max_length=20, validators=[gestion.models.cuenta_corriente_validator], verbose_name='N° Cuenta Corriente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(code='invalid', message='Solo se aceptan caracteres, y un mínimo de 2', regex='\\D[a-zA-Z]{2,}+')], verbose_name='Nombre de Fantasía'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre_rep_legal',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid', message='Solo se aceptan caracteres, y un mínimo de 2', regex='\\D[a-zA-Z]{2,}+')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(help_text='Ejemplo: +56912345678', max_length=18, validators=[django.core.validators.RegexValidator(code='invalid', message='Solo se aceptan dígitos y signo "+", siga el formato +56912345678', regex='^\\+1?\\d{9,15}$')], verbose_name='Teléfono/Celular'),
        ),
        migrations.AlterField(
            model_name='client',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(code='invalid', message='Solo se aceptan caracteres, y un mínimo de 2', regex='\\D[a-zA-Z]{2,}+')], verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='client',
            name='run_empresa',
            field=models.CharField(help_text='Ejemplo: 12345678-9', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Solo se aceptan dígitos y K, siga el formato 12345678-9', regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUT/RUN (Empresa)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='run_rep_legal',
            field=models.CharField(help_text='Ejemplo: 12345678-9', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Solo se aceptan dígitos y K, siga el formato 12345678-9', regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUN (Representante legal)'),
        ),
    ]
