# Generated by Django 5.2.7 on 2025-11-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0038_alter_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='n_trabajadores',
            field=models.IntegerField(max_length=10000, verbose_name='Trabajadores'),
        ),
    ]
