# Generated by Django 5.2.7 on 2025-11-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0039_alter_client_n_trabajadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='n_trabajadores',
            field=models.IntegerField(verbose_name='Trabajadores'),
        ),
    ]
