# Generated by Django 5.2.7 on 2025-11-23 12:23

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0042_client_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('export_client', 'Puede exportar clientes'), ('activate_client', 'Puede activar clientes'), ('view_deactivated_client', 'Puede ver clientes desactivados')]},
        ),
        migrations.AlterField(
            model_name='client',
            name='n_trabajadores',
            field=models.IntegerField(validators=[gestion.models.validate_max_trabajadores], verbose_name='Trabajadores'),
        ),
    ]
