# Generated by Django 5.1.5 on 2025-08-31 00:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 8, 31, 0, 3, 34, 551869, tzinfo=datetime.timezone.utc), verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=56912345678, help_text='Ejemplo: +56912345678', max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\+569\\d{8}$')], verbose_name='Teléfono/Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Opcional', null=True, upload_to='profile_pictures/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='profile',
            name='run',
            field=models.CharField(default=12345669, help_text='Ejemplo: 12345678-9', max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUN'),
            preserve_default=False,
        ),
    ]
