# Generated by Django 5.1.5 on 2025-08-31 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profile_date_of_birth_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(help_text='Ejemplo: +56912345678', max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+569\\d{8}$')], verbose_name='Teléfono/Celular'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='run',
            field=models.CharField(help_text='Ejemplo: 12345678-9', max_length=12, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUN'),
        ),
    ]
