# Generated by Django 5.1.5 on 2025-08-31 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(help_text='Ejemplo: +56912345678', max_length=12, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+569\\d{8}$')], verbose_name='Teléfono/Celular'),
        ),
    ]
