# Generated by Django 5.1.5 on 2025-09-02 18:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0006_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission', verbose_name='Permisos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(help_text='No se podrá cambiar', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_pfp.jpg', help_text='Opcional', upload_to='profile_pictures/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='run',
            field=models.CharField(error_messages={'invalid': 'El formato de RUN es incorrecto'}, help_text='Ejemplo: 12345678-9', max_length=12, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUN'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.ForeignKey(blank=True, default='Sin rol', help_text='Ingrese un rol, máximo de 40 caracteres.', max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', unique=True, verbose_name='Rol'),
        ),
    ]
