# Generated by Django 5.1.5 on 2025-09-02 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0007_role_permissions_alter_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.OneToOneField(blank=True, default='Sin rol', help_text='Ingrese un rol, máximo de 40 caracteres.', max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Rol'),
        ),
    ]
