# Generated by Django 5.1.5 on 2025-09-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Opcional', null=True, upload_to='profile_pictures/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='Sin cargo', help_text='Ingrese un cargo, máximo de 40 caracteres.', max_length=40, verbose_name='Cargo'),
        ),
    ]
