# Generated by Django 5.1.5 on 2025-09-02 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0009_remove_role_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission', verbose_name='Permisos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_pfp.jpg', help_text='Opcional', upload_to='profile_pictures/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.OneToOneField(blank=True, default='Sin rol', help_text='Ingrese un rol, máximo de 40 caracteres.', max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Rol'),
        ),
    ]
