# Generated by Django 5.2.7 on 2025-11-14 22:46

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0010_role_permissions_alter_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 11, 14, 22, 45, 10, 103325, tzinfo=datetime.timezone.utc), help_text='No se podrá cambiar', verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default=56985258525, help_text='Ejemplo: +56912345678', max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+569\\d{8}$')], verbose_name='Teléfono/Celular'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='run',
            field=models.CharField(blank=True, default=12345669, error_messages={'invalid': 'El formato de RUN es incorrecto'}, help_text='Ejemplo: 12345678-9', max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.OneToOneField(blank=True, default='Sin rol', max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Rol'),
        ),
    ]
