# Generated by Django 5.2.7 on 2025-11-14 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 11, 14, 22, 51, 19, 77927, tzinfo=datetime.timezone.utc), help_text='No se podrá cambiar', verbose_name='Fecha de nacimiento'),
        ),
    ]
