# Generated by Django 5.2.7 on 2025-11-14 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 11, 14, 22, 57, 19, 563235, tzinfo=datetime.timezone.utc), help_text='Ejemplo: 01/01/1990', verbose_name='Fecha de nacimiento'),
        ),
    ]
