# Generated by Django 5.2.7 on 2025-11-14 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Ejemplo: 01/01/1990', verbose_name='Fecha de nacimiento'),
        ),
    ]
